### ISSUE TITLE
How ti fit curve to data?

### ISSUE THREAD

**Issue by dejanmarich** [josemiotto/pylevy#10]
Hi, I'm trying to fit Levy distribution to empirical data. Can you provide some example or email me (dejan.marich@gmail.com), because I can't find anything in documentation.. thank you very much

**Comment by josemiotto** [comment]
Hi,

This is the documentation page for the functions of the package
https://pylevy.readthedocs.io/en/latest/levy.html#functions

Use the function *fit_levy*. The only necessary input is *x*, which is the
array with the data (not counts in bins, but the data itself)

best,
Jose

**Comment by dejanmarich** [comment]
```
from scipy.stats import norm
import matplotlib.pyplot as plt
import numpy as np
import levy

# Generate an array of 200 random sample from a normal dist with 
# mean 0 and stdv 1
random_sample = norm.rvs(loc=0,scale=1,size=200) 

# Distribution fitting
# norm.fit(data) returns a list of two parameters 
# (mean, parameters[0] and std, parameters[1]) via a MLE approach 
# to data, which should be in array form.
parameters = norm.fit(random_sample)

# now, parameters[0] and parameters[1] are the mean and 
# the standard deviation of the fitted distribution
x = np.linspace(-5,5,100)

# Generate the pdf (fitted distribution)
fitted_pdf = norm.pdf(x,loc = parameters[0],scale = parameters[1])
# Generate the pdf (normal distribution non fitted)
normal_pdf = norm.pdf(x)

#Levy
levy_fitted = levy.fit_levy(random_sample)

# Type help(plot) for a ton of information on pyplot
plt.plot(x,fitted_pdf,"red",label="Fitted normal dist",linestyle="dashed", linewidth=2)
plt.plot(x,normal_pdf,"blue",label="Normal dist", linewidth=2)
plt.plot(x, levy_fitted, "green", label="Levy fit", linewidth=2)
plt.hist(random_sample,normed=1,color="cyan",alpha=.3) #alpha, from 0 (transparent) to 1 (opaque)
plt.title("Normal distribution fitting")
# insert a legend in the plot (using label)
plt.legend()

# we finally show our work
plt.show()
```

I get error:
`ValueError: x and y must have same first dimension, but have shapes (100,) and (5,)`

Really can't get proper plot, and scipy.stats.levy is not working either, it's bugged.. thanx

**Comment by josemiotto** [comment]
The problem is that you are fitting the results of fit_levy as if it is a function of data, but it's only the parameters, that is why you get only an array of length 5. If you want to plot the PDF, you have to use the function **levy**. An example to get the PDF of the data you just fitted:
```
data = pylevy.random(1.5, 0, 0, 1, shape=200)
parameters = pylevy.fit_levy(data)
x = np.linspace(-5, 5, 100)
y = pylevy.levy(x, *parameters[:4])
```

I would highly recommend you that next time 1. you give the whole error text, in particular the line where you get the error, and 2. to read the documentation carefully, since it is clearly stated in the site I sent you what is the output of each function. To check easily, you could have made a `print(levy_fitted)` just after the levy_fitted calculation and you would have realized that it was not what you wanted
