### ISSUE TITLE
Parameterizations 0 and 1 use notation from unknown source

### ISSUE THREAD

**Issue by ragibson** [josemiotto/pylevy#13]
Where does the notation for your first two parameterizations come from?

https://github.com/josemiotto/pylevy/blob/64c525f273d00d89cbbe531a6557b17b74d18f88/levy/__init__.py#L61-L63

The documentation says this is "in the notation of Nolan", but this appears to be incorrect. He seems to use "alpha, beta, gamma, delta" notation: S(α,β,γ,δ;0) and S(α,β,γ,δ;1).

I've also seen some parameterizations c and mu in place of gamma and delta, respectively. Notably, these notation conventions seem to have the distribution scale come *before* the location, whereas pylevy does the opposite.

**Comment by josemiotto** [comment]
Nolan calls it gamma and delta and I call them my and sigma, without loss.
Where have you seen the other parameterizations?

**Comment by ragibson** [comment]
Voit's "The Statistical Mechanics of Financial Markets" uses

![levy_notation](https://user-images.githubusercontent.com/14023456/88055880-ad51af80-cb2d-11ea-9785-a45733688d15.png)

and e.g. Wikipedia introduces stable distributions with

![stable_dist](https://user-images.githubusercontent.com/14023456/88055982-d5411300-cb2d-11ea-9989-3fd8bc9f72f8.png)

but I'm not actually sure where this comes from originally (the sources here don't appear to use this notation).

**Comment by josemiotto** [comment]
I see, thanks for the Volt reference. I follow Nolan parametrization since this is the most quoted thing on Google Scholar. Personally, I'm not happy with that, because it's from a chapter of an unpublished book. I'd rather have Zolotarev as a reference, but I would agree in that it's a bit obscure to read. 

I'm **not** sure about the following statement, but I think that _because this distribution is stable_, the order of location and scale may be irrelevant, like in the Normal distribution.
