### ISSUE TITLE
Functions should warn about valid parameter ranges

### ISSUE THREAD

**Issue by ragibson** [josemiotto/pylevy#14]
Right now, pylevy throws errors or returns incorrect results when the parameters are invalid. This should probably print a warning or raise ValueError instead.

Moreover, while alpha values between 0.0 and 0.5 are completely valid, pylevy does not support them. There is a sentence in the documentation about this, but `levy.levy` just returns incorrect values and `levy.random` draws from the wrong distribution in these cases.

For instance,
```python
levy.levy(x=0, alpha=1.0, beta=1.1)
```
prints
```
1.0 25
1.1 105
This should not happen! If so, please open an issue in the pylevy github page please.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pylevy/levy/__init__.py", line 468, in levy
    low_lims = lower_limit[alpha_index, beta_index]
IndexError: index 105 is out of bounds for axis 1 with size 101
```

Perhaps more worringly,
```python
>>> levy.levy(x=0, alpha=0.5, beta=1.0)
0.24189505992004776
>>> levy.levy(x=0, alpha=0.2, beta=1.0)
0.24189505992004776
>>> levy.levy(x=0, alpha=0.0, beta=1.0)
/pylevy/levy/__init__.py:341: RuntimeWarning: invalid value encountered in double_scalars
  values = np.sin(np.pi * alpha / 2.0) * gamma(alpha) / np.pi * np.power(np.abs(x), -alpha - 1.0)
0.24189505992004776
>>> levy.levy(x=0, alpha=-1, beta=1.0)
0.24189505992004776
```

**Comment by josemiotto** [comment]
Well, by design that task is given to the Parameter class, which is used in the fit. If you use it in combination, there would be no issue, although I don't think you would get a warning, you are supposed to know what you are doing :) 
Also, there is no problem in the example you present: you are just in the extreme of the grid, and it's explicitly stated that alpha below 0.5 is not supported.

To answer your concern, I'm not raising an error, because when calling the function thousands of times you don't want that.

**Comment by ragibson** [comment]
Yes, I agree that it's a bit of a performance concern to put sanity checks in frequently called functions.

Perhaps this check should be added to the Parameter class in the future then.
